// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: regret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Ops           []*Operation           `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_regret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchRequest) GetOps() []*Operation {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	OpType        string                 `protobuf:"bytes,2,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_regret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *Operation) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *Operation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Results       []*OpResult            `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_regret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{2}
}

func (x *BatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchResponse) GetResults() []*OpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type OpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResult) Reset() {
	*x = OpResult{}
	mi := &file_regret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResult) ProtoMessage() {}

func (x *OpResult) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResult.ProtoReflect.Descriptor instead.
func (*OpResult) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{3}
}

func (x *OpResult) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *OpResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPrefix     string                 `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStateRequest) Reset() {
	*x = ReadStateRequest{}
	mi := &file_regret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStateRequest) ProtoMessage() {}

func (x *ReadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStateRequest.ProtoReflect.Descriptor instead.
func (*ReadStateRequest) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStateRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

type ReadStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStateResponse) Reset() {
	*x = ReadStateResponse{}
	mi := &file_regret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStateResponse) ProtoMessage() {}

func (x *ReadStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStateResponse.ProtoReflect.Descriptor instead.
func (*ReadStateResponse) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{5}
}

func (x *ReadStateResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_regret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPrefix     string                 `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_regret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{7}
}

func (x *CleanupRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

type CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_regret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_regret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_regret_proto_rawDescGZIP(), []int{8}
}

var File_regret_proto protoreflect.FileDescriptor

const file_regret_proto_rawDesc = "" +
	"\n" +
	"\fregret.proto\x12\tregret.v1\"Q\n" +
	"\fBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12&\n" +
	"\x03ops\x18\x02 \x03(\v2\x14.regret.v1.OperationR\x03ops\"S\n" +
	"\tOperation\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x17\n" +
	"\aop_type\x18\x02 \x01(\tR\x06opType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"Y\n" +
	"\rBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.regret.v1.OpResultR\aresults\"k\n" +
	"\bOpResult\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"1\n" +
	"\x10ReadStateRequest\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x01 \x01(\tR\tkeyPrefix\"@\n" +
	"\x11ReadStateResponse\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.regret.v1.RecordR\arecords\"\xb9\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\fH\x00R\x05value\x88\x01\x01\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.regret.v1.Record.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_value\"/\n" +
	"\x0eCleanupRequest\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x01 \x01(\tR\tkeyPrefix\"\x11\n" +
	"\x0fCleanupResponse2\xdd\x01\n" +
	"\x0eAdapterService\x12A\n" +
	"\fExecuteBatch\x12\x17.regret.v1.BatchRequest\x1a\x18.regret.v1.BatchResponse\x12F\n" +
	"\tReadState\x12\x1b.regret.v1.ReadStateRequest\x1a\x1c.regret.v1.ReadStateResponse\x12@\n" +
	"\aCleanup\x12\x19.regret.v1.CleanupRequest\x1a\x1a.regret.v1.CleanupResponseb\x06proto3"

var (
	file_regret_proto_rawDescOnce sync.Once
	file_regret_proto_rawDescData []byte
)

func file_regret_proto_rawDescGZIP() []byte {
	file_regret_proto_rawDescOnce.Do(func() {
		file_regret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_regret_proto_rawDesc), len(file_regret_proto_rawDesc)))
	})
	return file_regret_proto_rawDescData
}

var file_regret_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_regret_proto_goTypes = []any{
	(*BatchRequest)(nil),      // 0: regret.v1.BatchRequest
	(*Operation)(nil),         // 1: regret.v1.Operation
	(*BatchResponse)(nil),     // 2: regret.v1.BatchResponse
	(*OpResult)(nil),          // 3: regret.v1.OpResult
	(*ReadStateRequest)(nil),  // 4: regret.v1.ReadStateRequest
	(*ReadStateResponse)(nil), // 5: regret.v1.ReadStateResponse
	(*Record)(nil),            // 6: regret.v1.Record
	(*CleanupRequest)(nil),    // 7: regret.v1.CleanupRequest
	(*CleanupResponse)(nil),   // 8: regret.v1.CleanupResponse
	nil,                       // 9: regret.v1.Record.MetadataEntry
}
var file_regret_proto_depIdxs = []int32{
	1, // 0: regret.v1.BatchRequest.ops:type_name -> regret.v1.Operation
	3, // 1: regret.v1.BatchResponse.results:type_name -> regret.v1.OpResult
	6, // 2: regret.v1.ReadStateResponse.records:type_name -> regret.v1.Record
	9, // 3: regret.v1.Record.metadata:type_name -> regret.v1.Record.MetadataEntry
	0, // 4: regret.v1.AdapterService.ExecuteBatch:input_type -> regret.v1.BatchRequest
	4, // 5: regret.v1.AdapterService.ReadState:input_type -> regret.v1.ReadStateRequest
	7, // 6: regret.v1.AdapterService.Cleanup:input_type -> regret.v1.CleanupRequest
	2, // 7: regret.v1.AdapterService.ExecuteBatch:output_type -> regret.v1.BatchResponse
	5, // 8: regret.v1.AdapterService.ReadState:output_type -> regret.v1.ReadStateResponse
	8, // 9: regret.v1.AdapterService.Cleanup:output_type -> regret.v1.CleanupResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_regret_proto_init() }
func file_regret_proto_init() {
	if File_regret_proto != nil {
		return
	}
	file_regret_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_regret_proto_rawDesc), len(file_regret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_regret_proto_goTypes,
		DependencyIndexes: file_regret_proto_depIdxs,
		MessageInfos:      file_regret_proto_msgTypes,
	}.Build()
	File_regret_proto = out.File
	file_regret_proto_goTypes = nil
	file_regret_proto_depIdxs = nil
}
