use std::collections::HashMap;
use std::str::FromStr;

use tracing::warn;

use crate::storage::rocks::{RefEntry, RocksStore};
use crate::types::OpType;

use super::{
    AdapterBatchResponse, AdapterOpResult, CheckpointFailure, GetComparison, OpKind, OpStatus,
    Operation, RecordState, ReferenceModel, SafetyViolation, Tolerance,
};

pub struct BasicKvReference {
    rocks: RocksStore,
    hypothesis_id: String,
    run_id: String,
}

impl BasicKvReference {
    pub fn new(rocks: RocksStore, hypothesis_id: String) -> Self {
        Self {
            rocks,
            hypothesis_id,
            run_id: String::new(),
        }
    }

    /// The key prefix for this hypothesis + run in RocksDB.
    fn run_prefix(&self) -> String {
        format!("/ref/{}/{}/", self.hypothesis_id, self.run_id)
    }

    fn should_ignore_field(field: &str, tolerance: &Option<Tolerance>) -> bool {
        if let Some(t) = tolerance {
            t.structural.iter().any(|s| s.field == field && s.ignore)
        } else {
            false
        }
    }

    /// Apply a successful write to the reference state.
    fn apply_write(&self, op: &Operation) {
        match &op.kind {
            OpKind::Put { key, value } => {
                let version = self.rocks.ref_get(key).ok().flatten()
                    .map(|e| e.version + 1).unwrap_or(1);
                let _ = self.rocks.ref_put(key, &RefEntry { value: value.clone(), version });
            }
            OpKind::Delete { key } => {
                let _ = self.rocks.ref_delete(key);
            }
            OpKind::DeleteRange { start, end } => {
                let prefix = self.run_prefix();
                if let Ok(keys) = self.rocks.ref_range_keys(&prefix, start, end) {
                    for k in keys {
                        let _ = self.rocks.ref_delete(&k);
                    }
                }
            }
            OpKind::Cas { key, new_value, .. } => {
                let version = self.rocks.ref_get(key).ok().flatten()
                    .map(|e| e.version + 1).unwrap_or(1);
                let _ = self.rocks.ref_put(key, &RefEntry { value: new_value.clone(), version });
            }
            OpKind::EphemeralPut { key, value } => {
                let version = self.rocks.ref_get(key).ok().flatten()
                    .map(|e| e.version + 1).unwrap_or(1);
                let _ = self.rocks.ref_put(key, &RefEntry { value: value.clone(), version });
            }
            OpKind::IndexedPut { key, value, .. } => {
                let version = self.rocks.ref_get(key).ok().flatten()
                    .map(|e| e.version + 1).unwrap_or(1);
                let _ = self.rocks.ref_put(key, &RefEntry { value: value.clone(), version });
            }
            OpKind::SequencePut { .. } => {
                // Sequence key is generated by adapter — we don't know the key upfront
            }
            _ => {}
        }
    }

    /// Verify a read result against reference state.
    fn verify_read(
        &self,
        op: &Operation,
        result: &AdapterOpResult,
        tolerance: &Option<Tolerance>,
    ) -> Option<SafetyViolation> {
        let ignore_version = Self::should_ignore_field("version_id", tolerance);
        let parsed_status = OpStatus::from_str(&result.status).ok();

        match &op.kind {
            OpKind::Get { key, comparison } => {
                self.verify_get(op, key, comparison, result, parsed_status.as_ref(), ignore_version)
            }
            OpKind::List { start, end } => {
                self.verify_list(op, start, end, result)
            }
            OpKind::RangeScan { start, end } => {
                self.verify_range_scan(op, start, end, result, ignore_version)
            }
            _ => None,
        }
    }

    fn verify_get(
        &self,
        op: &Operation,
        key: &str,
        comparison: &GetComparison,
        result: &AdapterOpResult,
        parsed_status: Option<&OpStatus>,
        ignore_version: bool,
    ) -> Option<SafetyViolation> {
        let prefix = self.run_prefix();

        // Find the expected record based on comparison type
        let expected: Option<(String, RefEntry)> = match comparison {
            GetComparison::Equal => {
                self.rocks.ref_get(key).ok().flatten().map(|e| (key.to_string(), e))
            }
            GetComparison::Floor => {
                self.rocks.ref_floor(&prefix, key).ok().flatten()
            }
            GetComparison::Ceiling => {
                self.rocks.ref_ceiling(&prefix, key).ok().flatten()
            }
            GetComparison::Lower => {
                self.rocks.ref_lower(&prefix, key).ok().flatten()
            }
            GetComparison::Higher => {
                self.rocks.ref_higher(&prefix, key).ok().flatten()
            }
        };

        match expected {
            Some((expected_key, entry)) => {
                // Should return ok with value
                if parsed_status != Some(&OpStatus::Ok) {
                    return Some(SafetyViolation {
                        op_id: op.id.clone(),
                        op: format!("get_{}", comparison_str(comparison)),
                        expected: format!("ok key={} value={}", expected_key, entry.value),
                        actual: format!("status={}", result.status),
                    });
                }
                // Check value
                if let Some(actual_value) = &result.value {
                    if *actual_value != entry.value {
                        return Some(SafetyViolation {
                            op_id: op.id.clone(),
                            op: format!("get_{}", comparison_str(comparison)),
                            expected: format!("value={}", entry.value),
                            actual: format!("value={}", actual_value),
                        });
                    }
                }
                None
            }
            None => {
                // Should return not_found
                if parsed_status != Some(&OpStatus::NotFound) && parsed_status != Some(&OpStatus::Ok) {
                    // Some adapters return Ok with empty value for not_found on comparison gets
                    return None;
                }
                if parsed_status == Some(&OpStatus::Ok) && result.value.is_some() {
                    return Some(SafetyViolation {
                        op_id: op.id.clone(),
                        op: format!("get_{}", comparison_str(comparison)),
                        expected: "not_found".to_string(),
                        actual: format!("ok value={}", result.value.as_deref().unwrap_or("")),
                    });
                }
                None
            }
        }
    }

    fn verify_list(
        &self,
        op: &Operation,
        start: &str,
        end: &str,
        result: &AdapterOpResult,
    ) -> Option<SafetyViolation> {
        let prefix = self.run_prefix();
        let expected_keys = self.rocks.ref_range_keys(&prefix, start, end).unwrap_or_default();
        let actual_keys = result.keys.as_deref().unwrap_or(&[]);

        if expected_keys.len() != actual_keys.len() {
            return Some(SafetyViolation {
                op_id: op.id.clone(),
                op: "list".to_string(),
                expected: format!("{} keys", expected_keys.len()),
                actual: format!("{} keys", actual_keys.len()),
            });
        }

        // Verify exact sorted order
        for (i, (exp, act)) in expected_keys.iter().zip(actual_keys.iter()).enumerate() {
            if exp != act {
                return Some(SafetyViolation {
                    op_id: op.id.clone(),
                    op: "list".to_string(),
                    expected: format!("key[{}]={}", i, exp),
                    actual: format!("key[{}]={}", i, act),
                });
            }
        }
        None
    }

    fn verify_range_scan(
        &self,
        op: &Operation,
        start: &str,
        end: &str,
        result: &AdapterOpResult,
        ignore_version: bool,
    ) -> Option<SafetyViolation> {
        let prefix = self.run_prefix();
        let expected = self.rocks.ref_range_scan(&prefix, start, end).unwrap_or_default();
        let actual_records = result.records.as_deref().unwrap_or(&[]);

        if expected.len() != actual_records.len() {
            return Some(SafetyViolation {
                op_id: op.id.clone(),
                op: "range_scan".to_string(),
                expected: format!("{} records", expected.len()),
                actual: format!("{} records", actual_records.len()),
            });
        }

        // Verify exact sorted order + values
        for (i, ((exp_key, exp_entry), act)) in expected.iter().zip(actual_records.iter()).enumerate() {
            if *exp_key != act.key {
                return Some(SafetyViolation {
                    op_id: op.id.clone(),
                    op: "range_scan".to_string(),
                    expected: format!("record[{}].key={}", i, exp_key),
                    actual: format!("record[{}].key={}", i, act.key),
                });
            }
            if exp_entry.value != act.value {
                return Some(SafetyViolation {
                    op_id: op.id.clone(),
                    op: "range_scan".to_string(),
                    expected: format!("record[{}].value={}", i, exp_entry.value),
                    actual: format!("record[{}].value={}", i, act.value),
                });
            }
        }
        None
    }
}

impl ReferenceModel for BasicKvReference {
    fn process_response(
        &mut self,
        ops: &[Operation],
        response: &AdapterBatchResponse,
        tolerance: &Option<Tolerance>,
    ) -> Vec<SafetyViolation> {
        let mut failures = Vec::new();

        for (op, result) in ops.iter().zip(response.results.iter()) {
            if op.id != result.op_id {
                continue;
            }

            let parsed_status = OpStatus::from_str(&result.status).ok();

            let is_write = matches!(
                op.kind,
                OpKind::Put { .. } | OpKind::Delete { .. } | OpKind::DeleteRange { .. }
                | OpKind::Cas { .. } | OpKind::EphemeralPut { .. }
                | OpKind::IndexedPut { .. } | OpKind::SequencePut { .. }
            );

            if is_write && parsed_status == Some(OpStatus::Ok) {
                self.apply_write(op);
            }

            let is_read = matches!(
                op.kind,
                OpKind::Get { .. } | OpKind::List { .. } | OpKind::RangeScan { .. }
            );

            if is_read {
                if let Some(failure) = self.verify_read(op, result, tolerance) {
                    failures.push(failure);
                }
            }
        }

        failures
    }

    fn verify_checkpoint(
        &self,
        actual_state: &HashMap<String, Option<RecordState>>,
        tolerance: &Option<Tolerance>,
    ) -> Vec<CheckpointFailure> {
        let ignore_version = Self::should_ignore_field("version_id", tolerance);
        let prefix = self.run_prefix();
        let expected_all = self.rocks.ref_scan_all(&prefix).unwrap_or_default();

        let mut failures = Vec::new();

        // Build expected map
        let expected_map: HashMap<String, RecordState> = expected_all
            .into_iter()
            .map(|(k, e)| (k, RecordState { value: Some(e.value), version_id: e.version }))
            .collect();

        // Check all expected keys exist in actual
        for (key, exp_state) in &expected_map {
            let act = actual_state.get(key).cloned().flatten();
            match act {
                Some(act_state) => {
                    let value_mismatch = exp_state.value != act_state.value;
                    let version_mismatch = !ignore_version && exp_state.version_id != act_state.version_id;
                    if value_mismatch || version_mismatch {
                        failures.push(CheckpointFailure {
                            key: key.clone(),
                            expected: Some(exp_state.clone()),
                            actual: Some(act_state),
                        });
                    }
                }
                None => {
                    failures.push(CheckpointFailure {
                        key: key.clone(),
                        expected: Some(exp_state.clone()),
                        actual: None,
                    });
                }
            }
        }

        // Check for extra keys in actual that aren't in expected
        for (key, act) in actual_state {
            if !key.starts_with(&prefix) {
                continue;
            }
            if !expected_map.contains_key(key) {
                if let Some(act_state) = act {
                    failures.push(CheckpointFailure {
                        key: key.clone(),
                        expected: None,
                        actual: Some(act_state.clone()),
                    });
                }
            }
        }

        failures
    }

    fn snapshot_all(&self) -> HashMap<String, Option<RecordState>> {
        let prefix = self.run_prefix();
        let all = self.rocks.ref_scan_all(&prefix).unwrap_or_default();
        all.into_iter()
            .map(|(k, e)| (k, Some(RecordState { value: Some(e.value), version_id: e.version })))
            .collect()
    }

    fn key_prefix(&self) -> String {
        self.run_prefix()
    }

    fn set_run_id(&mut self, run_id: &str) {
        self.run_id = run_id.to_string();
    }

    fn clear(&mut self) {
        let prefix = self.run_prefix();
        if let Err(e) = self.rocks.ref_clear(&prefix) {
            warn!(error = %e, "failed to clear reference state");
        }
    }
}

fn comparison_str(c: &GetComparison) -> &'static str {
    match c {
        GetComparison::Equal => "equal",
        GetComparison::Floor => "floor",
        GetComparison::Ceiling => "ceiling",
        GetComparison::Lower => "lower",
        GetComparison::Higher => "higher",
    }
}
